name: Build Kernel Package
on: [push, pull_request, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build In Docker
        if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          BUILDUSER=kansei
          BUILDGROUP=Jinba-Ittai
          HOSTNAME=It-Just-Feels-Right
          cat << EOF > entrypoint.sh
          cd /build
          groupadd -r $BUILDGROUP
          useradd $BUILDUSER -g $BUILDGROUP -m
          passwd -d $BUILDUSER
          pacman -Syu --noconfirm --needed sudo base-devel git python-yaml
          printf '$BUILDUSER ALL=(ALL) ALL\\n' | tee -a /etc/sudoers
          chown -R $BUILDUSER:$BUILDGROUP ./
          sudo -u $BUILDUSER gpg --keyserver keyserver.ubuntu.com --recv-keys 38DBBDC86092693E
          sudo -u $BUILDUSER bash -c 'export MAKEFLAGS=j\$(nproc) && makepkg -s --noconfirm'
          EOF

          docker run -h $HOSTNAME -t -v $PWD:/build archlinux /bin/bash /build/entrypoint.sh

      - name: Print sha512sums
        if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
        run: sha512sum *.pkg.tar.*

      - name: Upload Built Packages
        if: ${{ !contains(github.event.head_commit.message, '[no build]') }}
        uses: actions/upload-artifact@v4
        with:
          name: built-packages
          path: ${{ github.workspace }}/*.pkg.tar.*

      - name: Create Tag
        if: ${{ !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') && github.event_name != 'pull_request' }}
        id: create_tag
        run: |
          source PKGBUILD
          echo "tag=${pkgver}" >> $GITHUB_OUTPUT
          echo $pkgver $pkgrel
      - name: Release
        if: ${{ !contains(github.event.head_commit.message, '[no rel]') && !contains(github.event.head_commit.message, '[no build]') && github.event_name != 'pull_request' }}
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.workspace }}/*.zip
            ${{ github.workspace }}/*.pkg.tar.*
          tag_name: v${{ steps.create_tag.outputs.tag }}
          name: ${{ steps.create_tag.outputs.tag }} - Release Jinba Ittai
          draft: ${{ contains(github.event.head_commit.message, '[draft]') }}
          prerelease: ${{ contains(github.event.head_commit.message, '[prerel]') }}
          body: |
            This is the same as the manual release from yesterday. These were built with the github runner rather than the arch build container on my selfhosting infra.
            'sudo pacman -U <file>' to install or insert into your build pipeline for your custom Arch-based composable immutable image or what have you.
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
